### PR TITLE
Feature/crosstalk (WIP)

### PR DESCRIPTION
**Pull request by timelyportfolio**
This represents a first pass at integrating [`crosstalk`](https://github.com/rstudio/crosstalk) in `timevis`.  I classify as a WIP since crosstalk is unstable and also I'm not sure if this fits in future plans or adheres to your coding style.  For now, I tried to code such that we can avoid hard dependency on `crosstalk` in the `DESCRIPTION`.

### to do

- [ ] add an example with another `htmlwidget`
- [ ] decide how to handle added or deleted items, since they will currently require a `key_`.  Also, `SharedData` on the R side will not know what to do with these changes.
- [ ] add a Shiny example using `SharedData` instead of the traditional Shiny event handling
- [ ] figure out why the `select` event gets fired twice in `timevis`.  I did not have time to explore cause.

### CODE REVIEW

**Comment by daattali** [comment]
Thanks for the very quick PR! I'll take a look sometime this week

**Comment by daattali** [comment]
It looks like docs for crosstalk are in the process of being generated? You probably know much better than I do if that's true? I just saw that http://rstudio.github.io/crosstalk/index.html went live yesterday hence my assumption. That might help me with making sense of your code since I've never played around with crosstalk yet

**Comment by daattali** [comment]
Regarding your point "decide how to handle added or deleted items" - is that something that isn't natural for crosstalk to deal with? Crosstalk assumes the dataframe that gets initializes is static throughout time?

**Comment by timelyportfolio** [comment]
Yes @daattali, there is not a built-in mechanism in `crosstalk` (unless @jcheng5 can tell me otherwise) to handle dynamic data.  However, this can be achieved with the current API but requires custom additions.

**Comment by daattali** [comment]
@timelyportfolio do you think you'll come back to this at some point, or is it ok if I close this PR?

**Comment by daattali** [comment]
Doesn't look like this will be revived at any point. I'd still welcome a PR , but it might have to be a fresh one since so much time has passed

**Pull request closed without merging**
