### PR TITLE
Nested Lists can now be passed through dataframeToD3

### PR DESCRIPTION
**Pull request by matthewstrasiotto**
I'd suggest squashing the merge on this because it got a bit messy on my end (I accidentally merged a branch for testing visjs upgrades into into my master branch, and then deleted all of my clean branches).

I cancelled my original PR because `dataframeToD3` was passing list cols correctly, but also passing empty list cols through, which was leading `vis.timeline` to style those groups as nesting groups.

### CODE REVIEW

**Comment by daattali** [comment]
I'm very late to this - but can you show an example of where this is useful?

**Comment by mstr3336** [comment]
Before I do so, I'd like to comment that on review of this over a year later, I jumped the gun in adding a `glue` dependency, which, from what I can see, is only used in helping format test case output. 

I wouldn't merge this without at least addressing that.
Also, this closely resembles #77 , and I think they're nearly the same PR with maybe the only difference being that one might use a more updated version of your upstream?

**Comment by daattali** [comment]
I havent looked closely at the two PRs. I was leaving them open and was planning on only looking into them once they become relevant. If you think they're very similar, they're both yours so feel free to change them

**Comment by matthewstrasiotto** [comment]
Closing this messy PR in favour of squashed #77

**Pull request closed without merging**
