### PR TITLE
minor documentation change

### PR DESCRIPTION
**Pull request by greg-minshall**
just the two files.  hopefully okay.  (a few extra changed-by-roxygen2-i-guess lines in man/timevis.Rd.)

### CODE REVIEW

**Comment by daattali** [comment]
there seem to be 2 separate issues in this PR, something about leaking information?

**Comment by daattali** [comment]
Have you tested this upgrade to 4.21? Every time I spend half an hour trying to upgrade timevis, I find various bugs. It's probably fixable but some of the R/JS code in the package would have to change and I haven't figured it out yet

**Comment by greg-minshall** [comment]
Dean,  are my most recent commits to my repository coming through on the old pull request?  apologies if so!

i am playing with 4.21, having wanted onIntialDrawComplete (but am not yet sure how to pass the "function" argument).  but, i didn't intend for my playing to escape.

is there a test suite that would show what you run into?  for my simple use, 4.21 appears fine.

**Comment by daattali** [comment]
Try running the example app (the one under inst/) and see that everything
works properly

**Comment by greg-minshall** [comment]
so, problem appears to be that in vis.js/Timeline 4.16.1, a date/time
could look like
----
2016-10-20 16:35
----
but in 4.21.1 (whatever), it needs to have a "T" instead of a space,
i.e.,
----
2016-10-20T16:35
----

if you want a pull request, i'd be happy to (a minor couple of
documentation changes to go along with it).  you might want to complain
to vis.js/Timeline, though?

**Comment by daattali** [comment]
Wow is that really the source of the difference? Thanks for debugging that.
I'll test that out and definitely submit an issue to visjs!

I'd be happy to get a PR! And even happier if it also fixes the existing
code examples (in the documentation and the sample app in inst/) :)

**Comment by greg-minshall** [comment]
okay, there should be a pull request.  please critique, if criticism
there be (especially the git bits)!

**Comment by daattali** [comment]
The title of this PR is "minor documentation change" - this is actually a PR for upgrading to visjs 4.21, correct?

**Comment by daattali** [comment]
@greg-minshall are you sure the `T` issue is all you need to fix visjs 4.21? Did you test this out with the visjs old and new javascript versions? I just tried running a very simple HTML page with a visjs timeline example, using visjs 4.21, and using the old date string (without `T`) and it worked just fine.

**Comment by daattali** [comment]
It looks like this time thing is only an issue in RStudio , that's why I didn't see it when I tested an HTML page.

I made an issue for upgrading visjs https://github.com/daattali/timevis/issues/50 and listed there all the outstanding regression bugs. There are two issues that are not solvable on my end, they are bugs I reported to visjs

**Comment by greg-minshall** [comment]
right.  my "testing" is flawed in that i don't use shiny.

**Comment by daattali** [comment]
@greg-minshall I'm doing some cleanup in this repo and closing this PR. After thinking about this some more and discussing with several people, it does not seem that "warning" users that the dataframe they pass into the function is available in javascript is necessary

**Comment by greg-minshall** [comment]
obviously, i disagree.  but, good luck with the upgrades, etc.!

(oddly, after some time, i've just started up a personal project that
will likely use timevis!)

**Comment by daattali** [comment]
I completely understand your disagreement. I'm adding some other improvements to the package, I hope you'll still find it useful

**Pull request closed without merging**
